"""Brand collections: fast-food chains, brands grouped by brand type, iOS apps, TV channels and carmakers.

Each row is (abbr, display name, category, primary color, secondary color, answer aliases).
The colors are the donor palette and white completes the third slot. Fast-food colors keep
the values snapped from the chains' original logos, so saved rounds look the same. Every
artwork variant (primary and alternates) is pinned in brand_artwork_sources.json and must
not show the brand's name, so players guess from the symbol alone. Hardee's and Carl's Jr.
share one Happy Star, so each accepts the other's name.
"""

FOOD = [
    ("MCD", "McDonald's", "Burgers", "FFCC00", "DA291C", ["McDonalds", "Mickey D's"]),
    ("BK", "Burger King", "Burgers", "D62300", "FF8732", ["BK"]),
    ("WEN", "Wendy's", "Burgers", "CF202E", "453635", ["Wendys"]),
    ("CFA", "Chick-fil-A", "Chicken", "E51636", "000000", ["Chick fil a", "CFA"]),
    ("KFC", "KFC", "Chicken", "E4002B", "000000", ["Kentucky Fried Chicken"]),
    ("POP", "Popeyes", "Chicken", "FF7D00", "D22630", ["Popeyes Louisiana Kitchen"]),
    ("SUB", "Subway", "Sandwiches", "008938", "F2B700", []),
    ("TB", "Taco Bell", "Mexican & Asian", "5B2994", "000000", []),
    ("ARB", "Arby's", "Sandwiches", "D71921", "000000", ["Arbys"]),
    ("SON", "Sonic", "Burgers", "EA0045", "0088D7", ["Sonic Drive-In"]),
    ("DQ", "Dairy Queen", "Coffee & Treats", "EE3E42", "007AC1", ["DQ"]),
    ("JACK", "Jack in the Box", "Burgers", "E31635", "000000", []),
    ("INO", "In-N-Out Burger", "Burgers", "E02A27", "FFCB05", ["In N Out", "In-N-Out"]),
    ("WHAT", "Whataburger", "Burgers", "FF770F", "000000", []),
    ("FIVE", "Five Guys", "Burgers", "C92027", "000000", []),
    ("CUL", "Culver's", "Burgers", "155195", "000000", ["Culvers"]),
    ("HARD", "Hardee's", "Burgers", "FFC72C", "CE1329", ["Hardees", "Carl's Jr.", "Carls Jr"]),
    ("CARL", "Carl's Jr.", "Burgers", "FFCF21", "E40425", ["Carls Jr", "Carl's Junior", "Hardee's", "Hardees"]),
    ("CHIP", "Chipotle", "Mexican & Asian", "AC2318", "441500", ["Chipotle Mexican Grill"]),
    ("PANDA", "Panda Express", "Mexican & Asian", "C02827", "1A1B21", []),
    ("DOM", "Domino's", "Pizza", "0090E2", "FF0000", ["Dominos", "Domino's Pizza"]),
    ("PH", "Pizza Hut", "Pizza", "EA1C24", "C70307", []),
    ("PAPA", "Papa Johns", "Pizza", "FF0000", "000000", ["Papa John's", "Papa John's Pizza"]),
    ("LC", "Little Caesars", "Pizza", "FF6000", "000000", []),
    ("DUNK", "Dunkin'", "Coffee & Treats", "EF6A00", "C63663", ["Dunkin", "Dunkin Donuts"]),
    ("STAR", "Starbucks", "Coffee & Treats", "00643C", "000000", []),
    ("ZAX", "Zaxby's", "Chicken", "0C1D42", "EA092A", ["Zaxbys"]),
    ("CANE", "Raising Cane's", "Chicken", "E71A2A", "FEBD11", ["Raising Canes", "Canes"]),
    ("BOJ", "Bojangles", "Chicken", "D0191A", "F8C437", []),
    ("CHECK", "Checkers", "Burgers", "E81D2D", "231F20", ["Rally's", "Rallys", "Checkers and Rally's"]),
]

BRAND = [
    ("PEPSI", "Pepsi", "Product", "005891", "EB1D39", ["Pepsi-Cola", "Pepsi Cola"]),
    ("PS", "PlayStation", "Product", "0070D1", "000000", ["Sony PlayStation", "PS5", "PS4", "Play Station"]),
    ("ANDROID", "Android", "Product", "34A853", "202124", ["Android OS", "Google Android"]),
    ("GATORADE", "Gatorade", "Product", "FF5000", "000000", ["Gatorade Thirst Quencher"]),
    ("MUSTANG", "Ford Mustang", "Product", "000000", "C8102E", ["Mustang"]),
    ("MC", "Mastercard", "Service", "EB001B", "F79E1B", ["MasterCard", "Master Card"]),
    ("UNITED", "United Airlines", "Service", "002244", "1414D2", ["United", "UA"]),
    ("DELTA", "Delta Air Lines", "Service", "E31937", "003366", ["Delta", "Delta Airlines"]),
    ("CHASE", "Chase", "Service", "117ACA", "000000", ["Chase Bank", "JPMorgan Chase", "JP Morgan Chase"]),
    ("ALLSTATE", "Allstate", "Service", "0033A0", "000000", ["Allstate Insurance"]),
    ("APPLE", "Apple", "Corporate", "000000", "A2AAAD", ["Apple Inc.", "Apple Computer", "Apple Computer Inc."]),
    ("MICROSOFT", "Microsoft", "Corporate", "F25022", "00A4EF", ["Microsoft Corporation", "Microsoft Corp", "Windows"]),
    ("META", "Meta", "Corporate", "0081FB", "192830", ["Meta Platforms", "Facebook", "Facebook Inc.", "FB"]),
    ("NBC", "NBC", "Corporate", "6E55DC", "FCCC12", ["National Broadcasting Company", "NBCUniversal", "NBC Universal"]),
    ("NIKE", "Nike", "Corporate", "111111", "FA5400", ["Nike Inc.", "Nike Swoosh"]),
    ("MJ", "Michael Jordan", "Personal", "000000", "CE1141", ["Jordan", "MJ", "Air Jordan", "Jumpman", "Jordan Brand", "Michael Jeffrey Jordan"]),
    ("PRINCE", "Prince", "Personal", "4B384C", "D4AF37", ["Prince Rogers Nelson", "The Artist Formerly Known as Prince", "The Artist", "TAFKAP"]),
    ("STONES", "The Rolling Stones", "Personal", "EB2E2E", "000000", ["Rolling Stones", "Stones", "The Stones"]),
    ("MRBEAST", "MrBeast", "Personal", "00ACD2", "E3457C", ["Mr Beast", "Mr. Beast", "Jimmy Donaldson", "Jimmy", "BEAST"]),
    ("TARGET", "Target", "Store", "CC0000", "000000", ["Target Corporation", "Tarzhay", "Tar-zhay", "SuperTarget"]),
    ("WALMART", "Walmart", "Store", "0053E2", "FFC220", ["Wal-Mart", "Wally World", "Walmart Supercenter"]),
    ("AMAZON", "Amazon", "Store", "FF9900", "232F3E", ["Amazon.com", "Amazon Prime"]),
    ("AE", "American Eagle", "Store", "182C52", "000000", ["American Eagle Outfitters", "AEO", "Am Eagle"]),
    ("LULU", "Lululemon", "Store", "D41935", "000000", ["Lululemon Athletica", "Lulu", "lulu lemon"]),
    ("TX", "Texas", "Place", "00205B", "BF0A30", ["Lone Star State", "Tejas", "State of Texas"]),
    ("CANADA", "Canada", "Place", "D52B1E", "000000", ["Canadian", "Great White North", "CAN"]),
    ("JAPAN", "Japan", "Place", "BC002D", "FFD700", ["Nippon", "Nihon", "Land of the Rising Sun", "JPN"]),
    ("CHICAGO", "Chicago", "Place", "41B6E6", "E4002B", ["Chi-Town", "Windy City", "Second City", "Chicago, Illinois", "CHI"]),
    ("MEXICO", "Mexico", "Place", "006847", "CE1126", ["México", "United Mexican States", "Estados Unidos Mexicanos", "MEX"]),
]

APP = [
    ("MAPS", "Maps", "Built-in", "76C63B", "3394E3", ["Apple Maps"]),
    ("WEATHER", "Weather", "Built-in", "387BD0", "FED500", ["Apple Weather"]),
    ("MESSAGES", "Messages", "Built-in", "34DA50", "1C1C1E", ["iMessage", "iMessages", "Apple Messages"]),
    ("FACETIME", "FaceTime", "Built-in", "1C1C1E", "31D950", ["Face Time"]),
    ("SAFARI", "Safari", "Built-in", "FE3C30", "1D9CF5", ["Apple Safari"]),
    ("SETTINGS", "Settings", "Built-in", "2E2E2F", "A6A6AA", ["iPhone Settings", "Apple Settings"]),
    ("CLOCK", "Clock", "Built-in", "EF8732", "202020", ["Apple Clock", "iPhone Clock"]),
    ("CALENDAR", "Calendar", "Built-in", "FE3C3B", "262626", ["Apple Calendar", "iCal", "iPhone Calendar"]),
    ("IG", "Instagram", "Social", "C837AB", "FF543E", ["Insta", "IG"]),
    ("SNAP", "Snapchat", "Social", "FFFC00", "000000", ["Snap", "Snap Chat"]),
    ("TIKTOK", "TikTok", "Social", "000000", "FE2C55", ["Tik Tok", "Musically", "Musical.ly"]),
    ("WA", "WhatsApp", "Social", "25D366", "075E54", ["Whats App", "Whatsapp Messenger"]),
    ("PIN", "Pinterest", "Social", "E60023", "111111", ["Pin", "Pins"]),
    ("DISCORD", "Discord", "Social", "5865F2", "23272A", ["Discord App"]),
    ("ROBLOX", "Roblox", "Games", "335FFF", "000000", []),
    ("MC", "Minecraft", "Games", "59AA43", "6D4E3B", ["Minecraft PE", "Minecraft Pocket Edition", "Minecraft Bedrock"]),
    ("AB", "Angry Birds", "Games", "D7002D", "000000", ["Angry Bird"]),
    ("POGO", "Pokémon GO", "Games", "FF1C1C", "000000", ["Pokemon GO", "Pokemon Go", "Pokémon Go", "Pokemon", "Pokémon"]),
    ("AMONG", "Among Us", "Games", "C51111", "FDD835", ["Among Us!", "Amogus"]),
    ("SURF", "Subway Surfers", "Games", "D50000", "4FC3F7", ["Subway Surfer", "Subway Surf"]),
    ("SPOTIFY", "Spotify", "Music & Video", "1ED760", "191414", ["Spotify Music"]),
    ("YT", "YouTube", "Music & Video", "FF0000", "282828", ["You Tube", "YT"]),
    ("NETFLIX", "Netflix", "Music & Video", "E50914", "000000", ["Netflix App"]),
    ("SHAZAM", "Shazam", "Music & Video", "0088FF", "000000", []),
    ("TWITCH", "Twitch", "Music & Video", "9146FF", "000000", ["Twitch TV", "TwitchTV"]),
    ("DUO", "Duolingo", "Everyday", "58CC02", "89E219", ["Duo", "Duo Lingo"]),
    ("GMAPS", "Google Maps", "Everyday", "EA4335", "34A853", ["GMaps", "Google Map"]),
    ("WAZE", "Waze", "Everyday", "33CCFF", "000000", []),
    ("VENMO", "Venmo", "Everyday", "008CFF", "1A1A1A", []),
    ("CASH", "Cash App", "Everyday", "00D632", "000000", ["CashApp", "Square Cash"]),
]

TV = [
    ("CBS", "CBS", "Broadcast", "033963", "000000", ["Columbia Broadcasting System", "CBS Television Network", "the Eye", "Eye network"]),
    ("ABC", "ABC", "Broadcast", "000000", "FFC20E", ["American Broadcasting Company", "ABC Television Network"]),
    ("FOX", "FOX", "Broadcast", "003998", "000000", ["Fox Broadcasting Company", "Fox Network", "Fox TV"]),
    ("PBS", "PBS", "Broadcast", "2638C4", "E2150C", ["Public Broadcasting Service"]),
    ("UNIVISION", "Univision", "Broadcast", "EE2737", "00A3E1", ["Univisión", "Univision Communications", "SIN", "Spanish International Network"]),
    ("TELEMUNDO", "Telemundo", "Broadcast", "EB1010", "911010", ["Telemundo Network", "Telemundo Television"]),
    ("HBO", "HBO", "Cable", "000000", "A7A9AC", ["Home Box Office"]),
    ("ESPN", "ESPN", "Cable", "E52534", "000000", ["Entertainment and Sports Programming Network", "Entertainment Sports Programming Network"]),
    ("CNN", "CNN", "Cable", "EC1C2E", "000000", ["Cable News Network"]),
    ("CC", "Comedy Central", "Cable", "FDC600", "CF4037", ["ComedyCentral", "Comedy Central Network", "The Comedy Channel", "Ha!"]),
    ("TNT", "TNT", "Cable", "000000", "D6001C", ["Turner Network Television"]),
    ("HALLMARK", "Hallmark Channel", "Cable", "61398E", "C9A227", ["Hallmark", "The Hallmark Channel", "Crown Media"]),
    ("MTV", "MTV", "Music & Pop", "FFCA0C", "007CB1", ["Music Television", "MTV Music Television"]),
    ("VH1", "VH1", "Music & Pop", "D30069", "E8B130", ["VH-1", "Video Hits One"]),
    ("BET", "BET", "Music & Pop", "000000", "E32F30", ["Black Entertainment Television", "BET Networks"]),
    ("CMT", "CMT", "Music & Pop", "E32F30", "F7DC02", ["Country Music Television"]),
    ("EENT", "E!", "Music & Pop", "EB2D2E", "000000", ["E", "E! Entertainment", "E! Entertainment Television", "E! Network"]),
    ("NICK", "Nickelodeon", "Kids", "FF6700", "8DC63F", ["Nick", "Nick Channel"]),
    ("CN", "Cartoon Network", "Kids", "000000", "A7A9AC", ["CN"]),
    ("DISNEY", "Disney Channel", "Kids", "28377D", "EE2724", ["The Disney Channel", "Disney"]),
    ("NICKJR", "Nick Jr.", "Kids", "FF7300", "00B5E2", ["Nick Jr", "Nick Junior", "Nickelodeon Junior"]),
    ("BOOM", "Boomerang", "Kids", "000000", "61A9D6", ["Boomerang from Cartoon Network", "Boomerang TV"]),
    ("PBSKIDS", "PBS Kids", "Kids", "99CC00", "2638C4", ["PBSKids", "PBS for Kids", "PBS Kids Channel"]),
    ("NAN", "Nick at Nite", "Kids", "F0CA00", "922B84", ["Nick at Night", "Nick@Nite", "Nick at Nite TV"]),
    ("DISC", "Discovery Channel", "Discovery & Lifestyle", "2D739F", "000000", ["Discovery", "The Discovery Channel"]),
    ("AP", "Animal Planet", "Discovery & Lifestyle", "0074FF", "346337", ["AnimalPlanet"]),
    ("HIST", "History", "Discovery & Lifestyle", "D99929", "ED1E25", ["History Channel", "The History Channel"]),
    ("NATGEO", "National Geographic", "Discovery & Lifestyle", "FFCC00", "000000", ["Nat Geo", "NatGeo", "National Geographic Channel", "Nat Geo TV"]),
    ("HGTV", "HGTV", "Discovery & Lifestyle", "009DD7", "45B26B", ["Home & Garden Television", "Home and Garden Television", "Home and Garden TV"]),
    ("TWC", "The Weather Channel", "Discovery & Lifestyle", "014F9D", "000000", ["Weather Channel"]),
]

CAR = [
    ("FORD", "Ford", "American", "00095B", "7F8C99", ["Ford Motor Company", "Ford Motor"]),
    ("CHEVY", "Chevrolet", "American", "D1A23A", "A7A9AC", ["Chevy"]),
    ("DODGE", "Dodge", "American", "CD3029", "000000", ["Dodge Brothers"]),
    ("CADILLAC", "Cadillac", "American", "000000", "A6192E", ["Caddy", "Caddie"]),
    ("JEEP", "Jeep", "American", "000000", "4E5B31", ["Willys Jeep"]),
    ("TESLA", "Tesla", "American", "E31937", "171A20", ["Tesla Motors", "Tesla Inc"]),
    ("TOYOTA", "Toyota", "Japanese & Korean", "EB0A1E", "58595B", ["Toyota Motor", "Toyota Motor Corporation"]),
    ("HONDA", "Honda", "Japanese & Korean", "DA251D", "000000", ["Honda Motor", "Honda Motor Company"]),
    ("NISSAN", "Nissan", "Japanese & Korean", "C3002F", "8C8C8C", ["Nissan Motor", "Nissan Motor Company"]),
    ("SUBARU", "Subaru", "Japanese & Korean", "013C74", "A7A9AC", ["Subaru Corporation", "Fuji Heavy Industries"]),
    ("MAZDA", "Mazda", "Japanese & Korean", "101010", "9E1B32", ["Mazda Motor", "Mazda Motor Corporation", "Toyo Kogyo"]),
    ("MITSU", "Mitsubishi", "Japanese & Korean", "E60012", "000000", ["Mitsubishi Motors", "Mitsubishi Motors Corporation"]),
    ("LEXUS", "Lexus", "Japanese & Korean", "000000", "8C8C8C", []),
    ("HYUNDAI", "Hyundai", "Japanese & Korean", "002C5F", "00AAD2", ["Hyundai Motor", "Hyundai Motor Company"]),
    ("MB", "Mercedes-Benz", "German", "333F48", "A4AAAE", ["Mercedes", "Benz", "Merc"]),
    ("BMW", "BMW", "German", "0066B1", "000000", ["Bayerische Motoren Werke", "Beemer", "Bimmer"]),
    ("AUDI", "Audi", "German", "BB0A30", "000000", ["Audi AG", "Auto Union"]),
    ("VW", "Volkswagen", "German", "001E50", "2058AF", ["VW", "Volkswagen AG"]),
    ("PORSCHE", "Porsche", "German", "A7002C", "F5CE65", ["Porsche AG", "Dr. Ing. h.c. F. Porsche"]),
    ("FERRARI", "Ferrari", "Italian", "E30016", "FFEC00", ["Scuderia Ferrari", "Ferrari S.p.A.", "Prancing Horse"]),
    ("LAMBO", "Lamborghini", "Italian", "B6A272", "111111", ["Lambo", "Automobili Lamborghini", "Lamborghini S.p.A."]),
    ("MASERATI", "Maserati", "Italian", "0C2340", "E21A22", ["Maserati S.p.A.", "Officine Alfieri Maserati"]),
    ("ALFA", "Alfa Romeo", "Italian", "D50D16", "157031", ["Alfa", "Alfa Romeo Automobiles", "ALFA"]),
    ("FIAT", "Fiat", "Italian", "A70230", "8A8D8F", ["FIAT", "Fiat Automobiles", "Fabbrica Italiana Automobili Torino"]),
    ("JAGUAR", "Jaguar", "British", "01422D", "9A9A9A", ["Jaguar Cars", "Jag", "Jaguar Land Rover"]),
    ("ASTON", "Aston Martin", "British", "004F32", "1A1A1A", ["Aston", "Aston Martin Lagonda", "AM"]),
    ("BENTLEY", "Bentley", "British", "576D5B", "333333", ["Bentley Motors"]),
    ("RR", "Rolls-Royce", "British", "281432", "0F059E", ["Rolls Royce", "Rolls-Royce Motor Cars", "Rolls"]),
    ("MCLAREN", "McLaren", "British", "FF8000", "54565A", ["McLaren Automotive", "McLaren Racing", "Mclaren F1"]),
    ("MINI", "Mini", "British", "120A08", "8A8D8F", ["MINI", "Mini Cooper", "Cooper"]),
]

LEAGUES = {
    "FOOD": {"label": "FAST FOOD", "conferences": ["Burgers", "Chicken", "Sandwiches", "Pizza", "Mexican & Asian", "Coffee & Treats"]},
    "BRAND": {"label": "BRANDS", "conferences": ["Product", "Service", "Corporate", "Personal", "Store", "Place"]},
    "APP": {"label": "APPS", "conferences": ["Built-in", "Social", "Games", "Music & Video", "Everyday"]},
    "TV": {"label": "TV", "conferences": ["Broadcast", "Cable", "Music & Pop", "Kids", "Discovery & Lifestyle"]},
    "CAR": {"label": "CARS", "conferences": ["American", "Japanese & Korean", "German", "Italian", "British"]},
}

ROSTERS = {"FOOD": FOOD, "BRAND": BRAND, "APP": APP, "TV": TV, "CAR": CAR}
SLUGS = {"FOOD": "fast-food", "BRAND": "brands", "APP": "apps", "TV": "tv", "CAR": "cars"}
